name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: plannify-truck-driver/github-actions/.github/workflows/build-push-tag.yml@main
    secrets: inherit
    with:
      images: |
        [
          {"image": "plannify-truck-driver/web-driver-app"}
        ]
      docker_build_args: |
        VITE_ENV=production
        VITE_VERSION=${{ github.ref_name }}
        VITE_API_URL=https://api2.plannify.be/driver/v1
