name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    uses: plannify-truck-driver/github-actions/.github/workflows/build-push-tag.yml@main
    secrets: inherit
    with:
      images: |
        [
          {"image": "plannify-truck-driver/web-driver-app"}
        ]
